In [ ]:
pip install html5lib

In [1]:
import pandas as pd
import lxml
import html5lib

In [2]:
#Ans 1 : 
a = [4, 8, 15, 16, 23, 42]

data = pd.DataFrame(a)
print(data)

    0
0   4
1   8
2  15
3  16
4  23
5  42

In [9]:
# Ans 2 : 
my_list = ["this", "is", "my", "series",2, 26,29,99,66,"end"]

data = pd.Series(my_list)
print(data)
type(data)

0      this
1        is
2        my
3    series
4         2
5        26
6        29
7        99
8        66
9       end
dtype: object

pandas.core.series.Series

In [12]:
#Ans 3 :
my_data = {
        "Name" : ["Alice","Bob","Claire"],
        "Age" : [25,30,27],
        "Gender" : ["Female","Male","Female"]
}

pd_data = pd.DataFrame(my_data)
print(pd_data)
print(type(pd_data))
print(type (pd_data["Name"]))

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [ ]:
# Ans 4 : 

"""
Data frame is an multi dimentional labeled array 
where as 
series is an one-dimensional labeled array

 In the above example when we check the data type of
 pd_data it is showing "pandas.core.frame.DataFrame"
 pd_data["Name"] is showing 'pandas.core.series.Series'

"""

In [17]:
# Ans 5 : 
# Column details and HEAD data of a data set

Random_data  = pd.read_csv("Youtube.csv")
print(Random_data.columns)
Random_data.head()
## remaining function below:

Index(['Video_link', 'thumbnail', 'Video_title', 'No_views', 'Video_publish'], dtype='object')

,Video_link,thumbnail,Video_title,No_views,Video_publish
0,https://www.youtube.com//watch?v=ecGcmstmnGA,['https://i.ytimg.com/vi/ecGcmstmnGA/hqdefault...,['Finally The Wait is Over ðŸ”¥ || Icse Batch Com...,"['16,401 views']",['3 days ago']
1,https://www.youtube.com//watch?v=08WWij66k8A,['https://i.ytimg.com/vi/08WWij66k8A/hqdefault...,"[""Best Strategy To Start Class-9th SST || Don'...","['16,615 views']",['5 days ago']
2,https://www.youtube.com//watch?v=bXpeyKIVioA,['https://i.ytimg.com/vi/bXpeyKIVioA/hqdefault...,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['29,740 views']",['9 days ago']
3,https://www.youtube.com//watch?v=YwxDKs7jNXs,['https://i.ytimg.com/vi/YwxDKs7jNXs/hqdefault...,['How To Plan For Class-11th || Perfect Strate...,"['51,105 views']",['10 days ago']
4,https://www.youtube.com//watch?v=dVq8dLd5zK4,['https://i.ytimg.com/vi/dVq8dLd5zK4/hqdefault...,['Strategy to Crack NEET in 1st Attempt ðŸ’ªðŸ’ª'],"['99,367 views']",['13 days ago']

In [ ]:
#deleting a Column
del_colm =Random_data.drop("thumbnail",axis=1)
(del_colm)

,Video_link,Video_title,No_views,Video_publish
0,https://www.youtube.com//watch?v=ecGcmstmnGA,['Finally The Wait is Over ðŸ”¥ || Icse Batch Com...,"['16,401 views']",['3 days ago']
1,https://www.youtube.com//watch?v=08WWij66k8A,"[""Best Strategy To Start Class-9th SST || Don'...","['16,615 views']",['5 days ago']
2,https://www.youtube.com//watch?v=bXpeyKIVioA,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['29,740 views']",['9 days ago']
3,https://www.youtube.com//watch?v=YwxDKs7jNXs,['How To Plan For Class-11th || Perfect Strate...,"['51,105 views']",['10 days ago']
4,https://www.youtube.com//watch?v=dVq8dLd5zK4,['Strategy to Crack NEET in 1st Attempt ðŸ’ªðŸ’ª'],"['99,367 views']",['13 days ago']
5,Video_link,Video_title,No_views,Video_publish
6,https://www.youtube.com//watch?v=33onjejJLDs,['Best Way To Start Class -9th English ðŸ’¥ || Ma...,"['3,182 views']",['3 hours ago']
7,https://www.youtube.com//watch?v=o3eOj-jhhfI,"[""PWSAT Is Back Again!! ðŸ”¥ || India's Biggest S...","['10,469 views']",['2 days ago']
8,https://www.youtube.com//watch?v=ecGcmstmnGA,['Finally The Wait is Over ðŸ”¥ || Icse Batch Com...,"['19,665 views']",['7 days ago']
9,https://www.youtube.com//watch?v=08WWij66k8A,"[""Best Strategy To Start Class-9th SST || Don'...","['18,708 views']",['9 days ago']
10,https://www.youtube.com//watch?v=bXpeyKIVioA,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['30,327 views']",['13 days ago']

In [15]:
#deleting a ROW
del_row =del_colm.drop(5,axis=0)
(del_row)

,Video_link,Video_title,No_views,Video_publish
0,https://www.youtube.com//watch?v=ecGcmstmnGA,['Finally The Wait is Over ðŸ”¥ || Icse Batch Com...,"['16,401 views']",['3 days ago']
1,https://www.youtube.com//watch?v=08WWij66k8A,"[""Best Strategy To Start Class-9th SST || Don'...","['16,615 views']",['5 days ago']
2,https://www.youtube.com//watch?v=bXpeyKIVioA,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['29,740 views']",['9 days ago']
3,https://www.youtube.com//watch?v=YwxDKs7jNXs,['How To Plan For Class-11th || Perfect Strate...,"['51,105 views']",['10 days ago']
4,https://www.youtube.com//watch?v=dVq8dLd5zK4,['Strategy to Crack NEET in 1st Attempt ðŸ’ªðŸ’ª'],"['99,367 views']",['13 days ago']
6,https://www.youtube.com//watch?v=33onjejJLDs,['Best Way To Start Class -9th English ðŸ’¥ || Ma...,"['3,182 views']",['3 hours ago']
7,https://www.youtube.com//watch?v=o3eOj-jhhfI,"[""PWSAT Is Back Again!! ðŸ”¥ || India's Biggest S...","['10,469 views']",['2 days ago']
8,https://www.youtube.com//watch?v=ecGcmstmnGA,['Finally The Wait is Over ðŸ”¥ || Icse Batch Com...,"['19,665 views']",['7 days ago']
9,https://www.youtube.com//watch?v=08WWij66k8A,"[""Best Strategy To Start Class-9th SST || Don'...","['18,708 views']",['9 days ago']
10,https://www.youtube.com//watch?v=bXpeyKIVioA,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['30,327 views']",['13 days ago']

In [20]:
#duplicate values find
del_row[del_row.duplicated()].count()

Video_link       0
Video_title      0
No_views         0
Video_publish    0
dtype: int64

In [33]:
#filtering values based on match 
value = del_row['Video_publish'][10]
del_row[del_row['Video_publish'] == value]

,Video_link,Video_title,No_views,Video_publish
4,https://www.youtube.com//watch?v=dVq8dLd5zK4,['Strategy to Crack NEET in 1st Attempt ðŸ’ªðŸ’ª'],"['99,367 views']",['13 days ago']
10,https://www.youtube.com//watch?v=bXpeyKIVioA,['Finally The Wait is OverðŸ”¥ || Launching Found...,"['30,327 views']",['13 days ago']

In [36]:
#Groupby opetation
del_row.groupby('Video_publish').count()

                 Video_link  Video_title  No_views
Video_publish
['10 days ago']           1            1         1
['13 days ago']           2            2         2
['2 days ago']            1            1         1
['3 days ago']            1            1         1
['3 hours ago']           1            1         1
['5 days ago']            1            1         1
['7 days ago']            1            1         1
['9 days ago']            2            2         2

In [ ]:
# Ans 6 : 

"""

Series      : 1 Dimension :	1D labeled homogeneous array, size  immutable.

Data Frames	: 2 Dimension :  	General 2D labeled, size  -mutable tabular structure with potentially heterogeneously typed columns.

Panel	    : 3	Dimension : General 3D labeled, size  -mutable array.

"""

In [37]:
# Ans 7 : 

author = ['Jitender', 'Purnima',
          'Arpit', 'Jyoti']
article = [210, 211, 114, 178]
 

auth_series = pd.Series(author)
article_series = pd.Series(article)
 

frame = {'Author': auth_series,
         'Article': article_series}
 

result = pd.DataFrame(frame)
 

print(result)

     Author  Article
0  Jitender      210
1   Purnima      211
2     Arpit      114
3     Jyoti      178